---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: serving-demo

commonLabels:
  component: data-science-project

resources:
- project.yml
- setup-serviceaccount.yml
- create-data-connection.yml
- add-model-job.yml
